config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :users
  resources :dogs


  resources :recipes do
    resource :comments
  end


  resources :foods


  get 'recipes/index'
  get 'foods/index'
  get 'public/main'
  get 'dogs/index'
  root to: 'public#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :recipe
end

app/models/dog.rb
class Dog < ApplicationRecord

  belongs_to :user, :optional => true
  has_many :recipes

  validates :name, presence: true
  validates :age, presence: true


end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  has_many :comments

  validates :title, presence: true
  validates :description, presence: true
  validates :ingredients, presence: true
  validates :directions, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :dogs

  def username
    return self.email.split('@')[0].capitalize
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_recipe

  def create
    @comment = @recipe.comments.create(comment_params)
    redirect_to @recipe
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  private
  def comment_params
    params.require(:comment).permit(:name, :content)
  end

   def set_recipe
      @recipe = Recipe.find(params[:recipe_id])
    end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
    before_action :set_dog, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user, except: [:show , :index]



  def index
    @dogs = Dog.all
  end

  def show
    end

  def new
    @dog = Dog.new
  end

  def edit
  end

  def create
  @dog = Dog.new(dog_params)
  @dog.user = current_user

  respond_to do |format|
    if @dog.save
      format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
      format.json { render :show, status: :created, location: @dog }
    else
      format.html { render :new }
      format.json { render json: @dog.errors, status: :unprocessable_entity }
    end
  end
end

  def update
  respond_to do |format|
    if @dog.update(dog_params)
      format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
      format.json { render :show, status: :ok, location: @dog }
    else
      format.html { render :edit }
      format.json { render json: @dog.errors, status: :unprocessable_entity }
    end
  end
end


  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_dog
    @dog = Dog.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dog_params
    params.require(:dog).permit(:name, :age)
  end


end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
      before_action :authenticate_user!, excpet: [:show , :index]
  def index
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def main
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
      before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  def index
      @recipes = Recipe.all
  end

def new
  @recipe = Recipe.new
end


def show
end


def edit
end

def create
@recipe = Recipe.new(recipe_params)

respond_to do |format|
  if @recipe.save
    format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
    format.json { render :show, status: :created, location: @recipe }
  else
    format.html { render :new }
    format.json { render json: @recipe.errors, status: :unprocessable_entity }
  end
end
end

def update
respond_to do |format|
  if @recipe.update(recipe_params)
    format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
    format.json { render :show, status: :ok, location: @recipe }
  else
    format.html { render :edit }
    format.json { render json: @recipe.errors, status: :unprocessable_entity }
  end
end
end


def destroy
  @recipe.destroy
  respond_to do |format|
    format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
    format.json { head :no_content }
  end
end


private
# Use callbacks to share common setup or constraints between actions.
def set_recipe
  @recipe = Recipe.find(params[:id])
end

# Never trust parameters from the scary internet, only allow the white list through.
def recipe_params
  params.require(:recipe).permit(:title, :description, :ingredients, :directions)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/comments/_comment.html.erb
<div>
  <strong><%= comment.name %> says:</strong>
  <%=comment.content %>
    <div class="comment-admin">
    <%= link_to "Edit", edit_recipe_comments_path(@recipe, comment)%>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_for [@recipe, comment] do  |f| %>
  <div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>

  <div class="field">
  <%= f.label :content, "Comment" %>
  <%= f.text_area :content %>
  </div>

  <div class= "actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/dogs/_form.html.erb
<%= form_with(model: dog, local: true) do |form| %>
  <% if dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_area :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form', dog: @dog %>


<%= link_to 'Show', @dog, :class => "btn btn-primary btn-sm" %>
<%= link_to 'Back', dogs_path, :class => "btn btn-primary btn-sm" %>

app/views/dogs/index.html.erb
<h1>Dogs</h1>



<table>
  <thead>
    <tr >
      <th class=" px-4">Name</th>
      <th class=" px-4">Age</th>
      <th class=" px-4">User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr class="text-center">
          <%= image_tag("img/am1.png") %>
        <td><%= dog.name %></td>
        <td><%= dog.age %></td>
        <td ><%= button_to 'Show', dog_path(:id => dog.id), :method => :get, :class => "btn btn-warning btn-sm"%></td>

        <%if current_user && current_user.admin? %>

	      <td><%= button_to 'Edit', edit_dog_path(:id => dog.id), :method => :get, :class => "btn btn-warning btn-sm" %></td>
        <td><%= button_to 'Destroy', dog_path(:id => dog.id), :method => :delete, :class => "btn btn-warning btn-sm" %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>








<br>

<%= link_to 'New Dog', new_dog_path, :class => "btn btn-primary btn-sm text-white" %>
<%= link_to 'Home', public_main_path, :class => "btn btn-primary btn-sm text-white" %>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Back', dogs_path, :class => "btn btn-primary btn-sm" %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @dog.age %>
</p>

<p>
  <strong>User:</strong>
  <%= @dog.user.username %>
</p>


<%= link_to 'Edit', edit_dog_path(@dog), :class => "btn btn-primary btn-sm" %>
<%= link_to 'Back', dogs_path, :class => "btn btn-primary btn-sm" %>

app/views/foods/index.html.erb
<h1>Your Food</h1>
<p>Tell us what you already have in your kitchen!</p>

<%= form_for @food do |f| %>
<div class="field">
  <%= f.label :Vegetable %> <br />
  <%= f.collection_check_boxes(:vegetable, {'carrots': 1, 'zuchini' :2, 'pumkin' :3}, left, first) %>



  <div class="form-check">
    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
    <label class="form-check-label" for="flexCheckDefault">
      Default checkbox
    </label>
  </div>
  <div class="form-check">
    <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" checked>
    <label class="form-check-label" for="flexCheckChecked">
      Checked checkbox
    </label>
  </div>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chowmedown</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <%=render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :ingredients %>
    <%= form.text_area :ingredients %>
  </div>

  <div class="field">
    <%= form.label :directions %>
    <%= form.text_area :directions %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>


<%= link_to 'Show', @recipe, :class => "btn btn-primary btn-sm" %>
<%= link_to 'Back', recipes_path, :class => "btn btn-primary btn-sm" %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>


<table>
  <thead>
    <tr >
      <th class=" px-4">Title</th>
      <th class=" px-4">Description</th>
      <th class=" px-4">Ingredients</th>
      <th class=" px-4">Directions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

<% @recipes.each do |recipe| %>
  <tr class="text-center">
    <td><%= recipe.title %></td>
    <td><%= recipe.description %></td>
    <td><%= recipe.ingredients %></td>
    <td><%= recipe.directions%></td>
    <td ><%= button_to 'Show', recipe_path(:id => recipe.id), :method => :get, :class => "btn btn-warning btn-sm"%></td>
<td><%= button_to 'Edit', edit_recipe_path(:id => recipe.id), :method => :get, :class => "btn btn-warning btn-sm" %></td>
    <td><%= button_to 'Destroy', recipe_path(:id => recipe.id), :method => :delete, :class => "btn btn-warning btn-sm" %></td>
  </tr>
<% end %>
</tbody>
</table>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path, :class => "btn btn-primary btn-sm" %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title%>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description%>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients%>
</p>
<p>
  <strong>Directions:</strong>
  <%= @recipe.directions%>
</p>

<div id="comments">
  <h1>Comments</h1>

  <%=  render @recipe.comments%>
  <h2> Add a Comment</h2>
  <%= render partial: "comments/form", locals: {comment: @recipe.comments.new}%>
  </div>


<%= link_to 'Edit', edit_recipe_path(@recipe), :class => "btn btn-primary btn-sm" %>
<%= link_to 'Back', recipes_path, :class => "btn btn-primary btn-sm" %>